language: node_js
node_js:
  - "lts/*"
env:
  - TS_VERSION="3.4.4"
before_script:
  - npm install -g prettier eslint typescript@$TS_VERSION @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint-config-prettier
script:
  - prettier -c "./**/*.ts"
  - eslint **/*.ts --max-warnings=0
